apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/security.kube-sentinel.io_clustertargets.yaml
- bases/security.kube-sentinel.io_securityassessments.yaml
- bases/security.kube-sentinel.io_scanruns.yaml
