//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIRemediationSpec) DeepCopyInto(out *AIRemediationSpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.SeverityFilter != nil {
		in, out := &in.SeverityFilter, &out.SeverityFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CategoryAllowlist != nil {
		in, out := &in.CategoryAllowlist, &out.CategoryAllowlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIRemediationSpec.
func (in *AIRemediationSpec) DeepCopy() *AIRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(AIRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactInputSpec) DeepCopyInto(out *ArtifactInputSpec) {
	*out = *in
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(ArtifactLocationRef)
		**out = **in
	}
	if in.ImageList != nil {
		in, out := &in.ImageList, &out.ImageList
		*out = make([]ImageArtifactRef, len(*in))
		copy(*out, *in)
	}
	if in.DigestList != nil {
		in, out := &in.DigestList, &out.DigestList
		*out = make([]ImageDigestRef, len(*in))
		copy(*out, *in)
	}
	if in.ManifestRef != nil {
		in, out := &in.ManifestRef, &out.ManifestRef
		*out = new(ArtifactLocationRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactInputSpec.
func (in *ArtifactInputSpec) DeepCopy() *ArtifactInputSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactLocationRef) DeepCopyInto(out *ArtifactLocationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactLocationRef.
func (in *ArtifactLocationRef) DeepCopy() *ArtifactLocationRef {
	if in == nil {
		return nil
	}
	out := new(ArtifactLocationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentSummary) DeepCopyInto(out *AssessmentSummary) {
	*out = *in
	in.LastRunAt.DeepCopyInto(&out.LastRunAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentSummary.
func (in *AssessmentSummary) DeepCopy() *AssessmentSummary {
	if in == nil {
		return nil
	}
	out := new(AssessmentSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTarget) DeepCopyInto(out *ClusterTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTarget.
func (in *ClusterTarget) DeepCopy() *ClusterTarget {
	if in == nil {
		return nil
	}
	out := new(ClusterTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTargetBootstrapPolicy) DeepCopyInto(out *ClusterTargetBootstrapPolicy) {
	*out = *in
	if in.AttachImagePullSecretRef != nil {
		in, out := &in.AttachImagePullSecretRef, &out.AttachImagePullSecretRef
		*out = new(LocalObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTargetBootstrapPolicy.
func (in *ClusterTargetBootstrapPolicy) DeepCopy() *ClusterTargetBootstrapPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterTargetBootstrapPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTargetList) DeepCopyInto(out *ClusterTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTargetList.
func (in *ClusterTargetList) DeepCopy() *ClusterTargetList {
	if in == nil {
		return nil
	}
	out := new(ClusterTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTargetSpec) DeepCopyInto(out *ClusterTargetSpec) {
	*out = *in
	out.KubeconfigRef = in.KubeconfigRef
	if in.NamespaceAllowlist != nil {
		in, out := &in.NamespaceAllowlist, &out.NamespaceAllowlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Output = in.Output
	out.Capabilities = in.Capabilities
	in.BootstrapPolicy.DeepCopyInto(&out.BootstrapPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTargetSpec.
func (in *ClusterTargetSpec) DeepCopy() *ClusterTargetSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTargetStatus) DeepCopyInto(out *ClusterTargetStatus) {
	*out = *in
	in.LastValidatedAt.DeepCopyInto(&out.LastValidatedAt)
	in.LastCredentialRotationAt.DeepCopyInto(&out.LastCredentialRotationAt)
	out.Capabilities = in.Capabilities
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTargetStatus.
func (in *ClusterTargetStatus) DeepCopy() *ClusterTargetStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureCondition) DeepCopyInto(out *FeatureCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureCondition.
func (in *FeatureCondition) DeepCopy() *FeatureCondition {
	if in == nil {
		return nil
	}
	out := new(FeatureCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureSpec) DeepCopyInto(out *FeatureSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureSpec.
func (in *FeatureSpec) DeepCopy() *FeatureSpec {
	if in == nil {
		return nil
	}
	out := new(FeatureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinalDecision) DeepCopyInto(out *FinalDecision) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]FinalDecisionReason, len(*in))
		copy(*out, *in)
	}
	in.DecidedAt.DeepCopyInto(&out.DecidedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinalDecision.
func (in *FinalDecision) DeepCopy() *FinalDecision {
	if in == nil {
		return nil
	}
	out := new(FinalDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinalDecisionReason) DeepCopyInto(out *FinalDecisionReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinalDecisionReason.
func (in *FinalDecisionReason) DeepCopy() *FinalDecisionReason {
	if in == nil {
		return nil
	}
	out := new(FinalDecisionReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageArtifactRef) DeepCopyInto(out *ImageArtifactRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageArtifactRef.
func (in *ImageArtifactRef) DeepCopy() *ImageArtifactRef {
	if in == nil {
		return nil
	}
	out := new(ImageArtifactRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageDigestRef) DeepCopyInto(out *ImageDigestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageDigestRef.
func (in *ImageDigestRef) DeepCopy() *ImageDigestRef {
	if in == nil {
		return nil
	}
	out := new(ImageDigestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectRef) DeepCopyInto(out *LocalObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectRef.
func (in *LocalObjectRef) DeepCopy() *LocalObjectRef {
	if in == nil {
		return nil
	}
	out := new(LocalObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputSpec) DeepCopyInto(out *OutputSpec) {
	*out = *in
	in.ReportStore.DeepCopyInto(&out.ReportStore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputSpec.
func (in *OutputSpec) DeepCopy() *OutputSpec {
	if in == nil {
		return nil
	}
	out := new(OutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteResourceRef) DeepCopyInto(out *RemoteResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteResourceRef.
func (in *RemoteResourceRef) DeepCopy() *RemoteResourceRef {
	if in == nil {
		return nil
	}
	out := new(RemoteResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportStoreSpec) DeepCopyInto(out *ReportStoreSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportStoreSpec.
func (in *ReportStoreSpec) DeepCopy() *ReportStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ReportStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanJobResourceSpec) DeepCopyInto(out *ScanJobResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanJobResourceSpec.
func (in *ScanJobResourceSpec) DeepCopy() *ScanJobResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ScanJobResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanPhaseStatus) DeepCopyInto(out *ScanPhaseStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanPhaseStatus.
func (in *ScanPhaseStatus) DeepCopy() *ScanPhaseStatus {
	if in == nil {
		return nil
	}
	out := new(ScanPhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanResourceSpec) DeepCopyInto(out *ScanResourceSpec) {
	*out = *in
	out.SecurityAssessment = in.SecurityAssessment
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanResourceSpec.
func (in *ScanResourceSpec) DeepCopy() *ScanResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ScanResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanRun) DeepCopyInto(out *ScanRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanRun.
func (in *ScanRun) DeepCopy() *ScanRun {
	if in == nil {
		return nil
	}
	out := new(ScanRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScanRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanRunList) DeepCopyInto(out *ScanRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScanRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanRunList.
func (in *ScanRunList) DeepCopy() *ScanRunList {
	if in == nil {
		return nil
	}
	out := new(ScanRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScanRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanRunSpec) DeepCopyInto(out *ScanRunSpec) {
	*out = *in
	out.AssessmentRef = in.AssessmentRef
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]ScanProfile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanRunSpec.
func (in *ScanRunSpec) DeepCopy() *ScanRunSpec {
	if in == nil {
		return nil
	}
	out := new(ScanRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanRunStatus) DeepCopyInto(out *ScanRunStatus) {
	*out = *in
	in.ArtifactScan.DeepCopyInto(&out.ArtifactScan)
	in.ClusterScan.DeepCopyInto(&out.ClusterScan)
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]FeatureCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetRunStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemoteResources != nil {
		in, out := &in.RemoteResources, &out.RemoteResources
		*out = make([]RemoteResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.FinalDecision != nil {
		in, out := &in.FinalDecision, &out.FinalDecision
		*out = new(FinalDecision)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanRunStatus.
func (in *ScanRunStatus) DeepCopy() *ScanRunStatus {
	if in == nil {
		return nil
	}
	out := new(ScanRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityAssessment) DeepCopyInto(out *SecurityAssessment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityAssessment.
func (in *SecurityAssessment) DeepCopy() *SecurityAssessment {
	if in == nil {
		return nil
	}
	out := new(SecurityAssessment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityAssessment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityAssessmentList) DeepCopyInto(out *SecurityAssessmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityAssessment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityAssessmentList.
func (in *SecurityAssessmentList) DeepCopy() *SecurityAssessmentList {
	if in == nil {
		return nil
	}
	out := new(SecurityAssessmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityAssessmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityAssessmentSpec) DeepCopyInto(out *SecurityAssessmentSpec) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]ScanProfile, len(*in))
		copy(*out, *in)
	}
	if in.ArtifactInput != nil {
		in, out := &in.ArtifactInput, &out.ArtifactInput
		*out = new(ArtifactInputSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AIRemediation != nil {
		in, out := &in.AIRemediation, &out.AIRemediation
		*out = new(AIRemediationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]FeatureSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Output.DeepCopyInto(&out.Output)
	if in.ScanResources != nil {
		in, out := &in.ScanResources, &out.ScanResources
		*out = new(ScanResourceSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityAssessmentSpec.
func (in *SecurityAssessmentSpec) DeepCopy() *SecurityAssessmentSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityAssessmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityAssessmentStatus) DeepCopyInto(out *SecurityAssessmentStatus) {
	*out = *in
	if in.LastRunRef != nil {
		in, out := &in.LastRunRef, &out.LastRunRef
		*out = new(LocalObjectRef)
		**out = **in
	}
	in.Summary.DeepCopyInto(&out.Summary)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityAssessmentStatus.
func (in *SecurityAssessmentStatus) DeepCopy() *SecurityAssessmentStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityAssessmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetCapabilitySpec) DeepCopyInto(out *TargetCapabilitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetCapabilitySpec.
func (in *TargetCapabilitySpec) DeepCopy() *TargetCapabilitySpec {
	if in == nil {
		return nil
	}
	out := new(TargetCapabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetCapabilityStatus) DeepCopyInto(out *TargetCapabilityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetCapabilityStatus.
func (in *TargetCapabilityStatus) DeepCopy() *TargetCapabilityStatus {
	if in == nil {
		return nil
	}
	out := new(TargetCapabilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetOutputSpec) DeepCopyInto(out *TargetOutputSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetOutputSpec.
func (in *TargetOutputSpec) DeepCopy() *TargetOutputSpec {
	if in == nil {
		return nil
	}
	out := new(TargetOutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRunStatus) DeepCopyInto(out *TargetRunStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRunStatus.
func (in *TargetRunStatus) DeepCopy() *TargetRunStatus {
	if in == nil {
		return nil
	}
	out := new(TargetRunStatus)
	in.DeepCopyInto(out)
	return out
}
