---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-sentinel-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.kube-sentinel.io
  resources:
  - clustertargets
  - scanruns
  - securityassessments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.kube-sentinel.io
  resources:
  - clustertargets/finalizers
  - scanruns/finalizers
  - securityassessments/finalizers
  verbs:
  - update
- apiGroups:
  - security.kube-sentinel.io
  resources:
  - clustertargets/status
  - scanruns/status
  - securityassessments/status
  verbs:
  - get
  - patch
  - update
